[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /opt/printer_data/run/klipper.sock

[machine]
provider: systemd_cli
validate_service: false

[authorization]
trusted_clients:
  0.0.0.0/0
cors_domains:
  *

[file_manager]
enable_object_processing: true
queue_gcode_uploads: true

[job_queue]
load_on_startup: true

[octoprint_compat]

[history]

# [zeroconf]
# mdns_hostname: deckhand

[mqtt]
address: home.assistant.lan
port: 1883
username: {secrets.mqtt.username}
password: {secrets.mqtt.password}

[power printer]
type: homeassistant
address: assistant.home.gleichmacher.us
port: 443
protocol: https
device: switch.ender_3_v3_se_uno_switch
token: {secrets.home_assistant.token}
status_delay: 1.0
off_when_shutdown: true
on_when_job_queued: true
locked_while_printing: true
restart_klipper_when_powered: true
restart_delay: 2
initial_state: off

[power overhead_lignt]
type: homeassistant
address: assistant.home.gleichmacher.us
port: 443
protocol: https
off_when_shutdown: false
locked_while_printing: false
restart_klipper_when_powered: false
device: light.3d_printer_room_socket_light
token: {secrets.home_assistant.token}
status_delay: 1.0
domain: light


# # Example configuration for ing with Tasmota firmware over mqtt
# [power overhead_light_mqtt]
# type: mqtt
# command_topic: cmnd/3dp_room_light/POWER
# # Tasmota uses "on" and "off" as the payload, so our template simply renders
# # the command
# command_payload:
#   {command}
# # There is no need to set the retain flag for Tasmota devices.  Moonraker
# # will use the query topic to initialize the device.  Tasmota will publish
# # all changes in state to the state topic.
# retain_command_state: False
# # To query a tasmota device we send the command topic without a payload.
# # Optionally we could send a "?" as the payload.
# query_topic: cmnd/3dp_room_light/POWER
# # query_payload: ?
# state_topic: stat/3dp_room_light/POWER
# # The response is either "ON" or "OFF".  Moonraker will handle converting to
# # lower case.
# state_response_template:
#   {payload}
# # Tasmota updates the state topic when the device state changes, so it is not
# # not necessary to query after a command
# query_after_command: False


# [update_manager KAMP]
# type: git_repo
# channel: dev
# path: /opt/printer_data/modules/KAMP
# origin: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
# managed_services: klipper
# primary_branch: main

## Uncomment the following lines if the stack is started with the spoolman profile.
## Add your printers IP address or hostname to the server url.
# 
# [spoolman]
# server: http://<yourprinter>/spoolman
